### ISSUE TITLE
Is there any way to access the queue length?

### ISSUE THREAD

**Issue by mendeljacks** [lpinca/stopcock#1]
The queue length is not exposed, is there any way to access the length of the queue?

A potential use case, 
do not add a batch job list if queue is already beyond a certain threshold

Another use case,
After each job is added or done a console.log is made which includes the current length of the queue to get an idea of how long is left untill the processing is complete.

**Comment by lpinca** [comment]
It's not very elegant but we can add a getter property to the returned function

https://github.com/lpinca/stopcock/blob/46b75b33c4b5d53a047b906cf2caac0ac0395b01/index.js#L99-L111

```js
Object.defineProperty(limiter, 'size', { get: () => queue.length });
```

If you have better ideas please share.

**Comment by mendeljacks** [comment]
Exposing the queue length as a getter method on the constructor function is sufficient.

For individual use cases people could write their own code.
 e.g:

var queueLimit = 600;
function queueMe(fn) {
 if ( stopcock.getQueue().length < queueLimit) 
     // Add items to the queue as normal
 }
}

**Comment by lpinca** [comment]
It's not on the constructor, there are no constructors. Here is an example usage of the above idea.

```js
const stopcock = require('stopcock');

function limitMyExecutionRate() {}

const limiter = stopcock(limitMyExecutionRate);

console.log(limiter.size);
```
